name: Build and Push Docker image to Docker Hub
on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GITDOCKER2_NARY }}
          password: ${{ secrets.GITDOCKER2_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: dockerpush2/
          push: true
          tags: tnary/gitdocker2:latest
